"""Auth

Revision ID: fbb20388e687
Revises: 0b05d9ea1be5
Create Date: 2023-04-28 13:52:43.809871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb20388e687'
down_revision = '0b05d9ea1be5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
